import { SpeakerEntity, ExhibitorEntity, AttendeeEntity } from "./types";

export const exhibitorsList: ExhibitorEntity[] = [
  {
    id: "ex_biocult",
    name: "BioCult Tech",
    focus: "Lab-grown alternative proteins and bioreactor scaling systems.",
    track: "Tech & Innovation",
    description: "BioCult Tech is pioneering cellular agriculture by designing industrial-scale modular bioreactors that make cellular beef, poultry, and fish alternatives commercially viable.",
    boothLocation: "Booth A-12",
    website: "https://biocult.tech",
    contactEmail: "match@biocult.tech",
    tier: "Platinum",
    logoAsset: "🔬"
  },
  {
    id: "ex_ecopack",
    name: "EcoPack Solutions",
    focus: "Zero-waste seaweed-based packaging materials.",
    track: "Sustainability & Packaging",
    description: "Developing bio-degradable polymer wraps using renewable marine algae that decay harmlessly in any domestic composting bin within 6 weeks.",
    boothLocation: "Booth B-05",
    website: "https://ecopacksolutions.org",
    contactEmail: "partner@ecopack.org",
    tier: "Platinum",
    logoAsset: "🌿"
  },
  {
    id: "ex_agridrone",
    name: "AgriDrone Logistics",
    focus: "Autonomous precision drone mapping and delivery.",
    track: "Supply Chain & Automation",
    description: "Aero-agricultural flight vectors combined with AI multispectral sensors to scan nutrients and deliver water or localized organic compounds with zero waste.",
    boothLocation: "Booth C-08",
    website: "https://agridronelogix.com",
    contactEmail: "fleet@agridrone.com",
    tier: "Gold",
    logoAsset: "🛸"
  },
  {
    id: "ex_verdevertical",
    name: "VerdeVerticals",
    focus: "Modular smart vertical hydroponic setups.",
    track: "Supply Chain & Automation",
    description: "Space-maximizing agricultural assemblies for metropolitan cores. Employs circular water recycling tech that saves up to 95% of fresh water.",
    boothLocation: "Booth C-14",
    website: "https://verdevertical.io",
    contactEmail: "grow@verdevertical.io",
    tier: "Gold",
    logoAsset: "🌱"
  },
  {
    id: "ex_freezefresh",
    name: "FreezeFresh Logix",
    focus: "Phase-change nitrogen cold chain monitoring.",
    track: "Supply Chain & Automation",
    description: "We design advanced refrigerated cargo storage using passive phase change elements, ensuring consistent sub-zero vaccine or frozen protein shipping without continuous grid-power drawing.",
    boothLocation: "Booth D-01",
    website: "https://freezefreshlogix.com",
    contactEmail: "coldchain@freezefresh.com",
    tier: "Silver",
    logoAsset: "❄️"
  },
  {
    id: "ex_mycelium",
    name: "Mycelium Foods",
    focus: "Whole-tissue meat replacements from fungi spores.",
    track: "Tech & Innovation",
    description: "Mycelium Foods brews dense, textured whole cuts like prime steaks and fillets entirely from fungi filaments root-systems, avoiding synthetic processes.",
    boothLocation: "Booth A-20",
    website: "https://myceliumfoods.com",
    contactEmail: "chef@myceliumfoods.com",
    tier: "Platinum",
    logoAsset: "🍄"
  },
  {
    id: "ex_aqualoop",
    name: "AquaLoop Marine",
    focus: "On-shore solar-powered marine aquaculture systems.",
    track: "Sustainability & Packaging",
    description: "Providing high-efficiency land-based seawater recycling containment systems for prawns and organic kelp, with full thermal and nutrient salvage.",
    boothLocation: "Booth B-19",
    website: "https://aqualoopmarine.com",
    contactEmail: "info@aqualoopmarine.com",
    tier: "Silver",
    logoAsset: "🌊"
  },
  {
    id: "ex_chocotrace",
    name: "ChocoTrace Block",
    focus: "Decentralized forest compliance tracking software.",
    track: "Consumer & Regulatory",
    description: "Blockchain consensus verification ledger that aggregates geolocation scans from cocoa farmers, proving absolute compliance with anti-deforestation standards.",
    boothLocation: "Booth E-04",
    website: "https://chocotrace.io",
    contactEmail: "compliance@chocotrace.io",
    tier: "Gold",
    logoAsset: "🍫"
  }
];

export const csvProfilesList = [
  {
    id: "feb8a00c-839e-4412-80c8-2e76765a1014",
    displayName: "CogniCo",
    companyDescription: "AI-Consulting for modern food systems to maximize agricultural yield, distribute automated software, and advise on sustainable crop deployment.",
    websiteUrl: "www.cognico.ca",
    countryRegion: "Canada",
    annualRevenue: "Pre-revenue",
    currentMarkets: "Canada",
    targetMarkets: "Canada, United States",
    importExportStatus: "Both",
    brandsRepresented: "AI",
    primarySectors: "Primary Production, Agritech & Smart Farming",
    targetBuyers: "Investors & VCs",
    boothSizeConfirmed: "Test Size",
    electricalNeeds: "Internet",
    exhibitorLeadId: "f81b29e2-57c4-4d4b-aefa-69591b91aae4"
  },
  {
    id: "e1160788-009e-4db2-a61c-a134bfd84634",
    displayName: "Test Org",
    companyDescription: "Sourcing partner researching sustainable tech implementation, primary farming analytics, and test simulations for metropolitan distribution channels.",
    websiteUrl: "",
    countryRegion: "Canada",
    annualRevenue: "Pre-revenue",
    currentMarkets: "Canada",
    targetMarkets: "Mexico",
    importExportStatus: "Exporter",
    brandsRepresented: "Test",
    primarySectors: "Primary Production, Agritech & Smart Farming",
    targetBuyers: "Government & Institutions",
    boothSizeConfirmed: "Test Size",
    electricalNeeds: "Test Electric",
    exhibitorLeadId: "0d8090e5-dd5b-4641-b968-35b72f78b531"
  },
  {
    id: "f4f09cb2-c7c0-49c0-b776-225ee4155cdb",
    displayName: "Food Forward",
    companyDescription: "Next-generation snack sourcing specializing in marine algae compositions, seaweed wraps, eco-packaging materials and alternative proteins.",
    websiteUrl: "https://www.cognico.ca/",
    linkedinUrl: "https://www.linkedin.com/in/cognico-test-3859263b9/",
    instagramUrl: "https://www.instagram.com/cognico_ai/",
    xUrl: "https://x.com/CogniCO_AI",
    countryRegion: "Canada",
    annualRevenue: "$100K – $500K",
    currentMarkets: "Canada, European Union, South America",
    targetMarkets: "Canada, European Union, South America",
    importExportStatus: "Both",
    brandsRepresented: "NLEats",
    primarySectors: "Primary Production, Agritech & Smart Farming, Sustainable Packaging, Start-Ups",
    targetBuyers: "Investors & VCs",
    boothSizeConfirmed: "8x8 Kiosk",
    electricalNeeds: "ALL",
    exhibitorLeadId: "74c53fc8-c454-4221-bab7-90b2f8e5b250"
  },
  {
    id: "9da28dbe-3b1e-4e60-834e-69e13f2ecf9c",
    displayName: "Cognico_test",
    companyDescription: "Early stage startup testing smart temperature cold-chains, automated crop sensor devices, and modern logistics management software.",
    websiteUrl: "www.cognico.ca",
    linkedinUrl: "https://ca.linkedin.com/company/cognico-ai-consulting",
    instagramUrl: "https://www.instagram.com/cognico.ca/",
    xUrl: "",
    countryRegion: "Canada",
    annualRevenue: "Pre-revenue",
    currentMarkets: "Canada, United States",
    targetMarkets: "United Kingdom, Canada, South America, Asia Pacific",
    importExportStatus: "Both",
    brandsRepresented: "Cognico_test",
    primarySectors: "Primary Production, Agritech & Smart Farming, Investment, Trade & Export, Food Processing & Equipment",
    targetBuyers: "Investors & VCs",
    boothSizeConfirmed: "Test Size",
    electricalNeeds: "Not needed",
    exhibitorLeadId: "291f8a8f-cd3a-4414-a282-0c39995ce1db"
  }
];

export const attendeesList: AttendeeEntity[] = csvProfilesList.map(csv => ({
  id: csv.id,
  displayName: csv.displayName,
  companyDescription: csv.companyDescription,
  email: csv.id === "feb8a00c-839e-4412-80c8-2e76765a1014" ? "cognico@nleats.com" : csv.id.slice(0, 8) + "@ffsummit.com",
  websiteUrl: csv.websiteUrl || "",
  linkedinUrl: csv.linkedinUrl || "",
  countryRegion: csv.countryRegion,
  annualRevenue: csv.annualRevenue,
  currentMarkets: csv.currentMarkets,
  targetMarkets: csv.targetMarkets,
  importExportStatus: csv.importExportStatus,
  brandsRepresented: csv.brandsRepresented,
  primarySectors: csv.primarySectors,
  targetBuyers: csv.targetBuyers,
  boothSizeConfirmed: csv.boothSizeConfirmed,
  electricalNeeds: csv.electricalNeeds,
  exhibitorLeadId: csv.exhibitorLeadId,
  role: csv.id === "feb8a00c-839e-4412-80c8-2e76765a1014" ? "Sponsor" : "Attendee"
}));

export const speakersList: SpeakerEntity[] = [
  {
    id: "884384d3-2093-41e2-8b7f-8299e0ba4615",
    createdAt: "2026-04-28 09:20:36.498008+00",
    fullName: "Alexander Kappes",
    email: "a.m.kappes@gmail.com",
    topicTitle: "AI at the Fence Line: What Livestock Technology Is Teaching the Rest of the Food System About Deploying AI to Farmers & Ranchers",
    bio: "As founder of Greener Herd, I built a digital livestock management platform serving smallholder farmers across the Middle East and Africa. In partnership with the UN World Food Programme and FAO, Greener Herd brings basic digital infrastructure, animal records, and nutrition guidance to overlooked ranching sectors.",
    sessionFormat: "Panel Discussion",
    avRequirements: "",
    submissionType: "propose_panel",
    nomineeName: "",
    nomineeEmail: "",
    linkedinUrl: "https://www.linkedin.com/in/alexander-m-kappes/",
    location: "Toronto, ON"
  },
  {
    id: "ad67408c-15ad-4164-b4f0-45a68dbba69d",
    createdAt: "2026-04-28 14:48:32.358737+00",
    fullName: "ASHLEY NICHOLLS",
    email: "ashley@reachag.ca",
    topicTitle: "Boots On The Ground Innovation",
    bio: "Through REACH Agriculture Strategies, Ashley focuses on human capital and workforce agility. Lasting agricultural innovation only occurs when frontline operational staff are fully trained and integrated.",
    sessionFormat: "Keynote",
    avRequirements: "",
    submissionType: "pitch_talk",
    nomineeName: "",
    nomineeEmail: "",
    linkedinUrl: "https://www.linkedin.com/in/ashley-nicholls-/",
    location: "Toronto, ON"
  },
  {
    id: "b8177664-818a-451b-a9b0-50522b1daa2b",
    createdAt: "2026-04-29 00:01:20.47657+00",
    fullName: "Saif",
    email: "saif.ahmed@nleats.com",
    topicTitle: "Agritech Challenges",
    bio: "Pioneering technology advisor sharing agricultural logistics templates and modern regional deployment insights.",
    sessionFormat: "Keynote",
    avRequirements: "Test requirements",
    submissionType: "pitch_talk",
    nomineeName: "",
    nomineeEmail: "",
    linkedinUrl: "https://ca.linkedin.com/in/saifahmed-",
    location: "Toronto, ON"
  },
  {
    id: "ba34ffa2-9653-467f-be17-d52d57024f9c",
    createdAt: "2026-05-02 19:12:44.750015+00",
    fullName: "Heidi M. Peterson",
    email: "hpeterson@sandcountyfoundation.org",
    topicTitle: "Soil health/Regenerative Agriculture",
    bio: "Dr. Heidi Peterson leads Sand County Foundation's agricultural research, promoting peer-to-peer on-farm soil conservation and watershed management models for global agriculture.",
    sessionFormat: "Keynote",
    avRequirements: "Presenter support",
    submissionType: "pitch_talk",
    nomineeName: "",
    nomineeEmail: "",
    linkedinUrl: "https://www.linkedin.com/in/heidi-peterson-5a931648/",
    location: "Toronto, ON"
  },
  {
    id: "9042fdd6-2d4b-48ea-b991-40730d3731aa",
    createdAt: "2026-05-04 15:23:11.928926+00",
    fullName: "Sophia Weiss",
    email: "sophia.weiss@grainmillers.com",
    topicTitle: "Scaling regenerative agriculture across the Canadian Prairies and building vibrant cross sector partnerships",
    bio: "Director of Sustainability and Regenerative Agriculture at Grain Millers Inc., bridging agronomy, corporate responsibility, and public health metrics to develop transparent food chains.",
    sessionFormat: "Fireside Chat",
    avRequirements: "",
    submissionType: "propose_panel",
    nomineeName: "",
    nomineeEmail: "",
    linkedinUrl: "https://www.linkedin.com/in/sophia-weiss/",
    location: "Toronto, ON"
  },
  {
    id: "a7fa3320-31be-4c0f-a682-6d2d6b513551",
    createdAt: "2026-05-05 14:33:59.087472+00",
    fullName: "Marc-André Roberge",
    email: "marc@nectar.buzz",
    topicTitle: "Leveraging agritech to benefit nature",
    bio: "Marc-André Roberge is the CEO and Co-founder of Nectar, a company using sensor mapping technologies to raise thriving honeybee colonies and protect pollination ecosystems.",
    sessionFormat: "Keynote",
    avRequirements: "Screen projection",
    submissionType: "pitch_talk",
    nomineeName: "",
    nomineeEmail: "",
    linkedinUrl: "https://www.linkedin.com/in/marcandreroberge/",
    location: "Toronto, ON"
  },
  {
    id: "97303fd5-bab6-47b3-b668-86de10442635",
    createdAt: "2026-05-05 14:40:39.446351+00",
    fullName: "Maha Tahiri",
    email: "maha@s2bgroup.com",
    topicTitle: "Food Forward in the GLP-1 Era: Reinventing Food Systems for a New Consumer-Patient",
    bio: "Dr. Maha Tahiri is a widely recognized nutrition strategist, advising global food CPG brands on nutrient-dense portfolios and structural food transformation.",
    sessionFormat: "Keynote",
    avRequirements: "",
    submissionType: "pitch_talk",
    nomineeName: "",
    nomineeEmail: "",
    linkedinUrl: "https://www.linkedin.com/in/mahatahiri/",
    location: "Toronto, ON"
  },
  {
    id: "206de90c-c5ac-4d84-855a-af7e149bb001",
    createdAt: "2026-05-08 18:43:36.35489+00",
    fullName: "Daniela Galloro",
    email: "marketing@biomemakers.com",
    topicTitle: "Beyond the Checklist: Leveraging AI to Verify Soil Health and Supply Chain Resilience",
    bio: "Dr. Jacob Parnell is the Director of Agronomy at Biome Makers, translating complex microbial datasets into actionable biological assets using smart prediction models.",
    sessionFormat: "Keynote",
    avRequirements: "microphone, screensharing",
    submissionType: "nominate_speaker",
    nomineeName: "Dr. Jacob Parnell",
    nomineeEmail: "jacob.parnell@biomemakers.com",
    linkedinUrl: "https://www.linkedin.com/in/jjacob-parnell/",
    location: "Toronto, ON"
  },
  {
    id: "89302393-6920-41df-a3b6-61ad346830c2",
    createdAt: "2026-06-08 13:02:09.087013+00",
    fullName: "Meifan Shi",
    email: "meifan@waterpointlane.com",
    topicTitle: "Invisible Infrastructure: AI reshaping food and agricultural investments",
    bio: "VC investor deploying capital targeting micro-factories, sensor automation, and agricultural genomics. Less theoretical talks, more actionable front-row insights.",
    sessionFormat: "Keynote",
    avRequirements: "",
    submissionType: "pitch_talk",
    nomineeName: "",
    nomineeEmail: "",
    linkedinUrl: "https://www.linkedin.com/in/meifanshi/",
    location: "Toronto, ON"
  }
];

export const initialSessions = [
  {
    id: "session_1",
    title: "Keynote: The Future of Lab-grown Protein Scaling",
    speaker: "Dr. Elena Rostova",
    speakerRole: "Chief Biotech Officer, Mycelium Frontiers",
    startTime: "09:00 AM",
    endTime: "10:15 AM",
    track: "Tech & Innovation",
    location: "Hall A (Main Stage)",
    description: "An exploration into structural scaling barriers for alternative cultured meats and mycelium-based whole cuts. Addresses growth media cost reductions and vessel hydraulic turbulence.",
    isBookmarked: true,
    attachmentUrl: "Slide_Alternative_Protein_Scaling.pdf"
  },
  {
    id: "session_2",
    title: "Panel: Seaweed & Bio-Materials in Circular Packaging",
    speaker: "Marcus Sterling & Linda Green",
    speakerRole: "Circular Ecology Advocates, EcoPack",
    startTime: "10:45 AM",
    endTime: "12:00 PM",
    track: "Sustainability & Packaging",
    location: "Room 204",
    description: "Real challenges in bio-grade structural strength, shelf-life oxygen barriers, cost comparison with traditional polymers, and marine biodegradable decomposition indexes.",
    isBookmarked: false,
    attachmentUrl: "Ecology_Report_Seaweed_Polymers.pdf"
  },
  {
    id: "session_3",
    title: "Masterclass: Drones & AI Imagery in Precision Farming",
    speaker: "Captain Sean Avery",
    speakerRole: "Director, AeroAgri Logix",
    startTime: "01:30 PM",
    endTime: "02:45 PM",
    track: "Supply Chain & Automation",
    location: "Demo Arena",
    description: "Live demonstration of multi-spectral drone payload configurations and fast aerial analytics pipelines to optimize fertilizer delivery in nitrogen-stressed croplands.",
    isBookmarked: false,
    attachmentUrl: "Drones_Agri_Workbook.pdf"
  },
  {
    id: "session_4",
    title: "Fireside: Blockchain Audits & Regulatory compliance",
    speaker: "Sola Vance & Naomi Klein",
    speakerRole: "Regulatory Specialists, ChocoTrace",
    startTime: "03:15 PM",
    endTime: "04:30 PM",
    track: "Consumer & Regulatory",
    location: "East Pavilion",
    description: "Exploring global chocolate deforestation compliance policies and how decentralized geofence smart contracts can prove compliance under strict EU supply rules.",
    isBookmarked: false,
    attachmentUrl: null
  }
];
